module ZammadAPI
  class Client
    RESOURCES: Hash[Symbol, untyped]
    CONVERSION_METHODS: Array[Symbol]
    ENV_OPTIONS: Hash[String, Symbol]

    attr_reader config: Config

    @transport: Transport

    def self.from_env: (**untyped overrides) -> Client

    def initialize: (**untyped options) -> void

    def group: () -> ResourceProxy
    def organization: () -> ResourceProxy
    def ticket: () -> ResourceProxy
    def ticket_article: () -> ResourceProxy
    def ticket_priority: () -> ResourceProxy
    def ticket_state: () -> ResourceProxy
    def user: () -> ResourceProxy

    def resource: (Symbol | String name) -> ResourceProxy
    def resource_names: () -> Array[Symbol]
    def me: () -> Resources::User
    def version: () -> String?

    def get: (String path, ?query: Hash[untyped, untyped]?) -> Response
    def post: (String path, ?query: Hash[untyped, untyped]?, ?body: untyped) -> Response
    def put: (String path, ?query: Hash[untyped, untyped]?, ?body: untyped) -> Response
    def delete: (String path, ?query: Hash[untyped, untyped]?) -> Response

    def with: (**untyped options) -> Client
    def with_transport: (untyped transport) -> Client
    def on_behalf_of: (String | Integer identifier) -> Client
                    | [T] (String | Integer identifier) { (Client) -> T } -> T
    def inspect: () -> String
    def method_missing: (Symbol, *untyped) -> untyped
    def respond_to_missing?: (Symbol, ?bool) -> bool

    private

    def raw: (Symbol method, String path, ?query: Hash[untyped, untyped]?, ?body: untyped) -> Response
    def unknown_resource_message: (Symbol | String) -> String
  end
end
