module ZammadAPI
  class Client
    RESOURCES: Hash[Symbol, untyped]
    CONVERSION_METHODS: Array[Symbol]

    attr_reader config: Config

    @transport: Transport

    def initialize: (**untyped options) -> void

    def group: () -> ResourceProxy
    def organization: () -> ResourceProxy
    def ticket: () -> ResourceProxy
    def ticket_article: () -> ResourceProxy
    def ticket_priority: () -> ResourceProxy
    def ticket_state: () -> ResourceProxy
    def user: () -> ResourceProxy

    def resource: (Symbol | String name) -> ResourceProxy
    def resource_names: () -> Array[Symbol]
    def with: (**untyped options) -> Client
    def on_behalf_of: (String | Integer identifier) -> Client
                    | [T] (String | Integer identifier) { (Client) -> T } -> T
    def inspect: () -> String
    def method_missing: (Symbol, *untyped) -> untyped
    def respond_to_missing?: (Symbol, ?bool) -> bool

    private

    def unknown_resource_message: (Symbol | String) -> String
  end
end
