module ZammadAPI
  class ResourceProxy
    SEARCH_MAX_PER_PAGE: Integer

    attr_reader resource_class: untyped

    @transport: Transport

    def initialize: (Transport, untyped resource_class) -> void
    def new: (?Hash[untyped, untyped] attributes) -> untyped
    def create: (?Hash[untyped, untyped] attributes) -> untyped
    def find: (Integer | String id) -> untyped
    def find_by: (**untyped) -> untyped
    def find_by!: (**untyped) -> untyped
    def exists?: (Integer | String id) -> bool
    def destroy: (Integer | String id) -> true
    def all: () -> Collection
    def where: (**untyped) -> Collection
    def search: (String term) -> Collection
    def inspect: () -> String

    private

    def collection: (String, String, ?query: Hash[Symbol, untyped], ?max_per_page: Integer, ?countable: bool) -> Collection
    def path: () -> String
  end
end
