# See https://github.com/sds/overcommit#configuration
#
# Install with: bundle exec overcommit --install

PreCommit:
  RuboCop:
    enabled: true
    on_warn: fail # Treat all warnings as failures
    command: ['bundle', 'exec', 'rubocop']

  TrailingWhitespace:
    enabled: true

  YamlSyntax:
    enabled: true

  BundleCheck:
    enabled: true

  RSpec:
    enabled: true
    description: 'Run the unit specs'
    command: ['bundle', 'exec', 'rspec', 'spec/unit']
