Naming/PredicateMethod:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

RSpec/DescribeMethod:
  Enabled: false

RSpec/ContextWording:
  Enabled: false
