module ZammadAPI
  module Resources
    class Base
      include AttributeAccess

      MAX_PER_PAGE: Integer

      attr_reader error: ValidationError?
      attr_reader transport: Transport

      @new_record: bool
      @destroyed: bool
      @error: ValidationError?
      @changes: Hash[Symbol, Array[untyped]]
      @related: Associations::Proxy?
      self.@related_class: untyped
      self.@declared_associations: Hash[Symbol, Hash[Symbol, untyped]]?

      def self.path: (String) -> void
      def self.resource_path: () -> String
      def self.from_response: (Transport, Hash[untyped, untyped] attributes) -> Base
      def self.associations: () -> Hash[Symbol, Hash[Symbol, untyped]]
      def self.related_class: () -> untyped
      def self.declared_associations: () -> Hash[Symbol, Hash[Symbol, untyped]]
      def self.belongs_to: (Symbol name, class_name: String, ?foreign_key: Symbol) -> void
      def self.has_many: (Symbol name, class_name: String, path: ^(Base) -> String) -> void

      def initialize: (Transport, ?Hash[untyped, untyped]? attributes) -> void
      def new_record?: () -> bool
      def persisted?: () -> bool
      def destroyed?: () -> bool
      def changes: () -> Hash[Symbol, Array[untyped]]
      def changed?: () -> bool
      def related: () -> Associations::Proxy
      def assign_attributes: (Hash[untyped, untyped] attributes) -> self
      def save: () -> bool
      def save!: () -> true
      def update: (Hash[untyped, untyped] attributes) -> bool
      def update!: (Hash[untyped, untyped] attributes) -> true
      def reload: () -> self
      def destroy: () -> true
      def inspect: () -> String

      private

      def mark_persisted!: () -> void
      def replace_attributes!: (Response, operation: String) -> void
      def write_attribute: (Symbol, untyped) -> untyped
      def create_record: () -> Response
      def update_record: () -> Response
      def member_path: () -> String
    end
  end
end
